### ISSUE TITLE
Unable to force-refresh

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#10]
Steps:
* 1 - Open ZIM lesfondamentaux.zim
* 2 - Reload page with CTRL+SHIFT+ R (with FF)

I get:
![image](https://user-images.githubusercontent.com/1029718/88560652-b6abb200-d02e-11ea-9afb-5b0ae8e62eaf.png)

I expect:
The very same welcome page

**Comment by ikreymer** [comment]
This is part of the spec, a 'hard reload' disables the service worker:
https://stackoverflow.com/questions/35628243/how-to-prevent-hard-reloads-from-bypassing-the-service-worker
https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#shift-reload

However, it should display a better error message when service workers are not available for any reason.. can see why this is not the case

**Comment by ikreymer** [comment]
Actually, seems that can force the iframe to do a regular `location.reload()`, thereby loading the page correctly with the service worker running.

**Comment by ikreymer** [comment]
Switching away from single-page app, as per #20 will break this, since `/A/...` urls are intercepted by the service worker to render correctly.

If this is an issue, then need to go back to the single page app, but have a redirect
So if the final url in the browser is:
`https://kiwix-serve/bouquineux/A/www.bouquineux.com/` then hard refresh will load an plain text/unrendered version.

To have the hard refresh work, we'll need to redirect back to:

`https://kiwix-serve/bouquineux/A/index.html?url=www.bouquineux.com/` and then hard refresh can work on this page.

**Comment by kelson42** [comment]
> Switching away from single-page app, as per #20 will break this

I don't get it. Considering that this ticket is a bug report, not clear what "will break a bug report" means?

**Comment by rgaudin** [comment]
Copying answer to that on Slack

> note that the one downside is that hard refresh will not work as it will disable the service worker.. the way around that would be to still use single page, but have these links redirect in sw to single page.. that's also doable but wanted to share this first

**Comment by ikreymer** [comment]
Yes, so I was saying it was fixed in this comment:

> Actually, seems that can force the iframe to do a regular `location.reload()`, thereby loading the page correctly with the service worker running.

But is not fixed again if not using single-page mode.

To make this work, we'll need to switch back to single page mode.

Both are possible:

`https://kiwix-serve/somezim/A/some.example.com/page.html` - hard refresh will load a page (currently as binary) without service worker

`https://kiwix-serve/somezim/A/index.html?url=some.example.com/page.html` - hard refresh can reload the iframe and render in service worker. But all urls will be viewed in single page like this (eg. A/index.html).

The main difference is simply that the first URL `https://kiwix-serve/somezim/A/some.example.com/page.html` will always redirect to the second `https://kiwix-serve/somezim/A/index.html?url=some.example.com/page.html` at the service worker level.

**Comment by rgaudin** [comment]
**Update**:

As of now, the force-refresh behavior is a bit different, and visually similar to #41, although what happens is a bit different.

When the user force a refresh, the service worker is not unregistered, but that very request (and its dependencies) is not attached to the service worker.

The result is we're getting the RAW article (with octet-stream mime).
