### ISSUE TITLE
Random features delivers a lot of « 404 »

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#108]
See for example

![IMG_2564](https://user-images.githubusercontent.com/1029718/234780634-4b872468-1ae7-4ad4-a811-e5493ebf5192.png)

Actually, most of the delivered URLs by the random button of https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2023-02/A/mesquartierschinois.wordpress.com/ are wrong

**Comment by benoit74** [comment]
Closing, this is mostly solved with zimit2: https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-03/

Mostly only because we still have few pages (e.g. https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-03/youtube.fuzzy.replayweb.page/embed/-KpLmsAR23I) which are purely black, because they are not meant to be loaded "standalone". This is not tracked in https://github.com/openzim/warc2zim/issues/240
