### ISSUE TITLE
Display in DEBUG all the important ZIM metadata

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#123]
If I look to a log I see something like this:
```
[DEBUG] Confirming output is writable using /output/tmpda8c84ht
[DEBUG] Title: Personal Security Checklist
[DEBUG] Language: en
[DEBUG] Favicon: https://github.githubassets.com/favicons/favicon.png
[DEBUG] Found WARC record for favicon: https://github.githubassets.com/favicons/favicon.png
```

I would like to list here all the important ZIM metadata, in particular the `Description` and the `LongDescription` which might just after make the whole process die (if bigger than the maximal size). See https://wiki.openzim.org/wiki/Metadata for the whole list of ZIM metadata.

**Comment by richterdavid** [comment]
I'd like to work on this.

**Comment by benoit74** [comment]
I don't think this issue is relevant anymore, at least not as it is phrased / oriented today.

What has already been decided for all scrapers is that we must use the `validate_metadata` methods from zimscraperlib to fail the scraper **early** when metadata used are incorrect: this displays the offending metadata value.

This still has to be implemented in warc2zim, I've just opened https://github.com/openzim/warc2zim/issues/123

Do we consider it would still help to display all metadata once validated, e.g. for the case where the validation checks are improperly implemented? If yes, this would anyway be better to do this in python-scraperlib so that all scrapers benefit from this enhancement.

**Comment by benoit74** [comment]
Oups, I'm wrong, the validation does not display the offending value. Maybe we can consider to also display the offending value.

**Comment by richterdavid** [comment]
> This still has to be implemented in warc2zim, I've just opened https://github.com/openzim/warc2zim/issues/123

That link goes to this issue; which issue did you mean @benoit74 ?

**Comment by kelson42** [comment]
> This still has to be implemented in warc2zim, I've just opened #123

I guess this is the wrong issue number

> Do we consider it would still help to display all metadata once validated, e.g. for the case where the validation checks are improperly implemented? If yes, this would anyway be better to do this in python-scraperlib so that all scrapers benefit from this enhancement.

Yes and yes

**Comment by benoit74** [comment]
> This still has to be implemented in warc2zim, I've just opened https://github.com/openzim/warc2zim/issues/123

Yes, proper issue is https://github.com/openzim/warc2zim/issues/235

> Yes and yes

Closing this issue then, we will implement the necessary in python scraperlib and next upgrade of the dependency in warc2zim will deploy it "automatically", I don't think we need to track this here.

**Comment by benoit74** [comment]
I've just opened it: https://github.com/openzim/python-scraperlib/issues/155

**Comment by kelson42** [comment]
Last comment mostly invalidated by newly created ticket at scraperlib. @benoit74 thx

**Comment by benoit74** [comment]
> Last comment mostly invalidated by newly created ticket at scraperlib. @benoit74 thx

Next time I will open the ticket before closing the other one ^^

https://github.com/openzim/warc2zim/issues/235 is indeed a different thing. I will most probably implement it, but it is not necessary. It is not urgent because we anyway validate metadata now with recent scraperlib, the goal of 235 is to do it as early as possible, i.e. enhance current behavior where validation is done a bit late since it is not done in the "early check" done by zimit but after the crawl and after some processing of warc2zim.
