### ISSUE TITLE
Rethink dependency to zimscraperlib ?

### ISSUE THREAD

**Issue by mgautierfr** [openzim/warc2zim#131]
Warc2zim is depending of zimscraperlib (openzim/python-scraperlib).

It is nice as we reuse some tools implemented there:
- stream_file
- setlocale, get_language_details, Locale
- convert_image, resize_image
- Creator
- get_mime_for_name
- StaticItem

But in the same time, we also need to install a lot of unnecessary dependencies (for us):
- yt-dlp
- iso-639
- colorthief
- lxml

Other dependencies we use (directly or not):
- requests (we could use it directly to download the one file we may have to download: favicon)
- python-resize-image and optimize-images (use to resize favicon)
- Babel
- file-magic
- libzim (we should have it as direct dependency)
- beautifulsoup4 (we already have it as direct dependency)

I wonder how we could simplify this a bit. Is it worth it ?
Maybe split scrapper lib ?

**Comment by mgautierfr** [comment]
No real problem.
Just that I was surprise that I have to install all this for a tool doing a "local" transformation.
And that I had to patch it (not difficultly) to be able to use a custom version of (python-)libzim.

**Comment by benoit74** [comment]
I think this concern is general to all scrapers. Maybe we should move this issue to python-scraperlib.

I also think the current situation is a compromise between the simplicity of maintaining (and installing) one lib for all scrapers vs. installing many unneeded dependencies. 

My feeling is that it is important that all scrapers depends on python-scraperlib(s) for operations they have in common (e.g. favicon resizing) so that we stop to duplicate logic. And I have to be convinced that the price to pay to create and maintain multiple python-scraperlibs for each kind of usage is worth it (my gut feeling is that defining these usages is a complex task because each scraper needs different kinds of dependencies).

**Comment by rgaudin** [comment]
I understand the concern and have been tempted myself to split it but it never stood the pros/cons exercice: The thing is there is no argument in favor beside “I'm bringing-in a lot of dependencies that I don't need”… which doesn't matter much for a scraper. The external ones can be ignored if you know what you will be using (libmagic is important for zim module but ffmpeg is obviously only used for videos).

Maintaining multiple libraries, and fixing all scrapers to use them instead feels like an unnecessary burden.

**Comment by kelson42** [comment]
It seems that we are almost all of us at the same level of pragmatism. If nobody comes with a solution to achieve a smarter deps mgmt easily, then I would propose to close as WONTFIX.

**Comment by kelson42** [comment]
Closing as it seems, to me at least, there is a consensus to keep current architecture.
