### ISSUE TITLE
Handle external links in warc2zim without SW

### ISSUE THREAD

**Issue by mgautierfr** [openzim/warc2zim#137]

**Comment by Jaifroid** [comment]
Does this issue refer to marking external links, e.g. with `target= "_blank"`, so that they will be opened outside the scope of the webview or iframe?

It might be worth adding handling of PDF opening / download, as they can't be opened in sandboxed webviews or iframes in Chromium browsers, and should probably be treated the same way as external links. (I just spent a lot of time coding for this in the PWA, because there are some really problematic cases: PDF "links" that are in fact html `meta http-equiv` redirects to the underlying PDF. On Android, these have to be downloaded *after* following the http-equiv redirect.

**Comment by mgautierfr** [comment]
> Does this issue refer to marking external links, e.g. with target= "_blank", so that they will be opened outside the scope of the webview or iframe?

Changing the html content for external links is an open question. It SEEMS that the consensus it that is would be to complex to have a generic way of doing it.
Same for changing the behavior of pdf link, we may have to do something on them at zim creation level but it is a bit out of scope for now.

The main idea here is, at zim file creation, detect which url are pointing to content in the archive and which ones are not. Based on this, we rewrite "internal" url and keep "external" url as it is.
For dynamic content (from js) we cannot do this check and so it will be to the "server" to detect asked url is not present and propose to open an external link.

**Comment by Jaifroid** [comment]
OK, thanks for explanation. So I guess we'll still need logic in readers that have sandboxed webviews / iframes, to detect external links and/or PDFs. That's fine. It is indeed pretty complex to detect sometimes, so maybe too complex to work this out when converting WARC to ZIM, and not the job of the converter.

**Comment by Jaifroid** [comment]
I had forgotten that there's interesting discussion of this "boundary problem" in #65. It's a real challenge.

**Comment by mgautierfr** [comment]
Fixed by #142
