### ISSUE TITLE
Zimit2 lowtechmagazin scrape seems to be missing content

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#167]
See:
* https://dev.library.kiwix.org/viewer#low-tech-solutions/
* https://dev.library.kiwix.org/viewer#offline-reading/
* https://dev.library.kiwix.org/viewer#donate/

All available links at https://dev.library.kiwix.org/viewer#solar.lowtechmagazine.com_en_all_2024-01/solar.lowtechmagazine.com/

**Comment by benoit74** [comment]
Problem is that these are kind of weird URLs with a space before and a space after:

![image](https://github.com/openzim/warc2zim/assets/7102089/06ed2ee8-b0b3-4e40-b58b-586035187608)

**Comment by rgaudin** [comment]
> Problem is that these are kind of weird URLs with a space before and a space after:

This is a rewriting issue ; the page is in the ZIM and reachable via correct URL

**Comment by Jaifroid** [comment]
Oh, I noticed this and thought it was a problem with my algorithm for checking if links are external to the ZIM (client-side). I therefore added a line removing any extraneous spaces before and after hyperlink URLs (when clicking on said links), then it works. 

I realize now I should have reported this -- thought it was something wombat would deal with normally, as I'm having to bypass wombat for checking these links (only on click) in order to check the true underlying URL.

**Comment by benoit74** [comment]
I confirm issue is fixed, last ZIM is OK
