### ISSUE TITLE
Random feature broken

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#17]
The random feature, provided by the taskbar, but also by almost (if not all) readers is currently broken as it changes the URL to a random choice of one from the `A/` namespace.

As all WARC items are currently being stored in `A/`, that allows Random to redirect to CSS, JS or even binary content which is not wanted.

@mgautierfr, with the coming removal of namespaces, how do you see this feature evolve? Should it be limited to `text/html` articles at the libkiwix level?

**Comment by mgautierfr** [comment]
Yes, I've face the same problem.
For now I've fix this by limiting to `text/html` indeed (https://github.com/kiwix/kiwix-lib/blob/libzim_next/src/reader.cpp#L168-L187)

Another possibility is to move the random feature in libzim and make the libzim based on the fact that the entry has a title in the dirent. If there is no title, we can assume this is a css/js/image, or a html not intended to be handle/presented as an article.

On new zim file, we may introduce a metadata listing the "end user"(articles) entries.
This could be specified with the new `getHint` method of the article/entry in the new writer api (https://github.com/openzim/libzim/issues/364)

**Comment by ikreymer** [comment]
In addition to only selecting HTML, the other part to this is kiwix-serve should load the page via a viewer url, for example, instead of `/A/example.com/page.html`, the link should be `/A/viewer.html#url=https://example.com/page.html`
This would be the same behavior for the search/suggestion results. Perhaps the viewer url can be specified as a special metadata entry? eg. `/M/replay_url` contains `/A/viewer.html#url=${url}` or something like that

**Comment by kelson42** [comment]
@jaifroid @mossroy I would like to include you to this discussion as Kiwix JS might be one of the most impacted port.

**Comment by Jaifroid** [comment]
Well, it's easy (now) for us to test the MIME type for html only, but I don't understand why some ZIMs are using the article namespace for non-article content... That breaks the openzim spec.

**Comment by mgautierfr** [comment]
>  I don't understand why some ZIMs are using the article namespace for non-article content... That breaks the openzim spec.

Indeed, warc2zim should not put non-article content in `A` namespace... with the current spec.
The plan is to hide the namespaces, the spec will change : https://github.com/openzim/libzim/issues/325

**Comment by rgaudin** [comment]
> Well, it's easy (now) for us to test the MIME type for html only, but I don't understand why some ZIMs are using the article namespace for non-article content... That breaks the openzim spec.

Because those ZIMs are created from WARC files and that would mean rewriting all links in payload and some of the HTTP headers. Since we are about to remove the namespaces, it makes sense to figure how this is gonna work in a namespace-less context instead of doing this painful work that might be useless in a very short time.

**Comment by rgaudin** [comment]
btw, the spec requires to only put the body in `A/` ; don't know any single ZIM that does this 😶

**Comment by Jaifroid** [comment]
FYI, Kiwix JS used to respect the spec, and injected the article HTML into the `iframe.body` instead of `iframe.documentElement`. However, because the article HTML always included the head tags, and wasn't a pure body fragment, this produced a technically non-valid page, so it was changed a couple of years ago.. Now I understand why it was originally written that way!

@kelson42 I think the description at https://wiki.openzim.org/wiki/Article_Format should be changed to reflect reality (though if namespaces really are disappearing despite #20 maybe a bigger rewrite is needed). I guess that's a separate but related issue.
