### ISSUE TITLE
Native suggestions are broken

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#18]
Suggestions (not Xapian based) fail. This is, I believe the same root cause like #17.

**Comment by rgaudin** [comment]
The suggestion system is based on a xapian index of the titles of articles. Current codebase sets an empty title on all articles. We need to fix that.

**Comment by kelson42** [comment]
@rgaudin This is a bit more complicated:
* We have a ZIM native title index which should work and is used by Kiwix JS (and this has nothing to do with Xapian)
* We have a Xapian title index which is used by Kiwix ports based on the Kiwix-lib

Considering that the Xapian has nothing to do with the ZIM format and is optional in the libzim, I would really prefer to have the native index of title working properly as well. I should not tell this, but actually the ZIM title index itself is optional as well in the ZIM spec (to the contrary to the URL index) ;)... but concretly there would is no (suggestion) search in Kiwix JS (and probably any other ZIM reader which is not Kiwix) if no title index.

**Comment by kelson42** [comment]
pinging @Jaifroid

**Comment by Jaifroid** [comment]
When you say "suggestions" do you mean search results?

As I understand it, libzim also uses the title pointer list if a Xapian index isn't present, so it's the universal fall-back. And titles can be derived from the URL index where URLs are also effectively titles -- I think mwoffliner does that to save space. Kiwix JS (and Kiwix JS Windows) cannot read the Xapian index because a Xapian Emscripten port would be very complicated and ZSTD is more urgent. On Wikipedia ZIMs, basic title search is "good enough" (you can find almost anything) because Wikipedia includes so many variants (including wrong spellings) of article titles.

It would be important for us for the native title index to work on wzrc2zim, unless someone can help us with the port of libzim to asm/wasm... But even on principle, the ZIM should have a documented way of accessing titles.
