### ISSUE TITLE
Fulltext search does not work for the moment

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#19]
Because the URL of the articles are not the same a the URL to display the article.

**Comment by rgaudin** [comment]
There are two different issues here:
- The full-text index is disabled (`language=""` on Creator).
- `should_index` returns False always.

This was done on purpose as we know that indexing the content would lead to the broken url issue you are mentioning: due to the single-page-app, returning links to articles would be useless and we'd like the search engine to return SPA-aware links instead.

This will either gets unblocked by removing the SPA #20 or add a libzim|kiwix feature to change links of search results

**Comment by kelson42** [comment]
We can consider that the libzim will implement soon a solution to decouple article URL / indexed content. See https://github.com/openzim/libzim/issues/384.
