### ISSUE TITLE
Consider abandoning single page app approach

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#20]
WebReplay.js works like a single page app and this is why so far we follow that approach to keep as much as possible of the standard WebReplay.js code base and don't create new problems.

Unfortunately this approach creates a lots of problems with our current Kiwix readers like:
* Native suggestions are broken #18 
* Random feature broken #17 
* Fulltext search does not work for the moment #19 (probably fixeable properly by extending libzim fulltext search/indexer feature set)
* Maybe even https://github.com/kiwix/kiwix-lib/issues/391 

And probably a few other things.

So far, I don't really understand how much effort would be needed to get HTML content is proper/directly viewable HTML pages. What here exactly the challenges?

**Comment by kelson42** [comment]
This would not be my prefered approach but maybe we could setup redirects in (ZIM or HTML) "A/" ?

**Comment by mgautierfr** [comment]
I've just check it on kiwix-lib side and in fact, it may not work at all :/

The kiwix-lib server is pretty simple and map almost one to one the url path and the entry path in the zim file.

https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L929-L948

So if the url is `https://example.com/zim_name/A/foo/bar.html`, kiwix-serve will search for the entry `foo/bar.html` in `A` namespace in `zim_name` zim file.
But if the url is `https://example.com/zim_name/A/viewer.html#url=https://example.com/page.html`, it will search for the entry `viewer.html#url=https://example.com/page.html` in `A` namespace.
And obviously `viewer.html#url=https://example.com/page.html` doesn't exist. `viewer.html` yes, `page.html` yes, but not the full path.

**Comment by ikreymer** [comment]
Not using this approach would be undoing everything that has been done so far :)
What is needed to make this work is either customizable redirects or just exposing everything via JSON, and then viewer could provide its own title bar. 

(Note that the UI is actually pretty separate from the WARC->ZIM conversion itself and not necessarily tied to warc2zim)

> I've just check it on kiwix-lib side and in fact, it may not work at all :/
> 
> The kiwix-lib server is pretty simple and map almost one to one the url path and the entry path in the zim file.
> 
> https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L929-L948
> 
> So if the url is `https://example.com/zim_name/A/foo/bar.html`, kiwix-serve will search for the entry `foo/bar.html` in `A` namespace in `zim_name` zim file.
> But if the url is `https://example.com/zim_name/A/viewer.html#url=https://example.com/page.html`, it will search for the entry `viewer.html#url=https://example.com/page.html` in `A` namespace.
> And obviously `viewer.html#url=https://example.com/page.html` doesn't exist. `viewer.html` yes, `page.html` yes, but not the full path.

I'm not sure I understand the exact issue..  the hashtag path is designed to just load a static file, nothing needs to happen for this..

The main change to support all of this is just to be able to customize the redirect, like here:
https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L676
and
https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L909

instead of redirecting to `A/https://example.com/page.html` the redirect would be to:
`A/viewer.html#url=https://example.com/page.html`. Perhaps this could be stored in the metadata as a template, like

`M/redirectUrl` and contain something like `A/viewer#url=${URL}` otherwise default to `${URL}` to determine the redirect string.

Another option is just to expose these all as JSON APIs and then the client-side viewer can handle it. It seems like this is being done for suggestions only, but not for other endpoints?
https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L596

**Comment by kelson42** [comment]
> Another option is just to expose these all as JSON APIs and then the client-side viewer can handle it. It seems like this is being done for suggestions only, but not for other endpoints?
> https://github.com/kiwix/kiwix-lib/blob/master/src/server.cpp#L596

This is a kiwix-serve specific API, here we talk about the ZIM format and what is stored in it. The only API possible is what is specified in the ZIM specification.

**Comment by kelson42** [comment]
@mgautierfr Could we by any change extend the ZIM format to store an URL fragment (#.... or ?....) in a redirect?
@ikreymer Does warc2zim can deal properly with HTML redirects (like `<meta http-equiv = "refresh" content = "2; url = ..." />`).

**Comment by ikreymer** [comment]
> This is a kiwix-serve specific API, here we talk about the ZIM format and what is stored in it. The only API possible is what is specified in the ZIM specification.

Oh, I thought kiwix-lib is used in all platforms.. If so, might make sense to have a consistent API across all platforms that exposes suggestions, search, random, etc.. and then the JS client can work using those APIs

> @mgautierfr Could we by any change extend the ZIM format to store an URL fragment (#.... or ?....) in a redirect?
> @ikreymer Does warc2zim can deal properly with HTML redirects (like `<meta http-equiv = "refresh" content = "2; url = ..." />`).

I'm not sure how this would work exactly, but in theory, yes.. Just would need to go through the viewer.

Actually, there is another option.. if the requests are made to within the scope of the service worker, eg. `/<zim>/A/__random?` or `/<zim/>/A/__search` the service worker could take over those as well..

**Comment by kelson42** [comment]
@ikreymer Typically here it would be outside a SW, so for example (1) request `https://example.com/zim_name/A/foo/bar.html` (2) response html redirect with `url=A/viewer.html#url=https://example.com/page.html`. I believe that could work. To achieve that we would have to:
* Move all what is in `A/` currently somewhere else
* For each HTML article create a corresponding HTML article in `A/` with the same title and a meaningfull URL which would basically be a simple HTML redirect.

AFAIK that would solve #17 and #18.

**Comment by mgautierfr** [comment]
Make sense. But it would somehow double the number of article.
And we would have to use the content of the article as data to index for the redirect.

But it should be possible.

**Comment by ikreymer** [comment]
Hm, creating a duplicate list of entries just to do a redirect doesn't seem like a good idea, and wouldn't the search results just show `<meta ...>` and not actual content, you'd have the same problem?

Actually, there is no reason why this has to be single page.. the service worker can also intercept any `/A/<...>` url and render the correct page.. That would not be hard to support, but you'd still need a separate endpoint from which to load raw content, eg. `/api/raw?article=...`

**Comment by kelson42** [comment]
> Hm, creating a duplicate list of entries just to do a redirect doesn't seem like a good idea, and wouldn't the search results just show `<meta ...>` and not actual content, you'd have the same problem?

Yes, this is not really pretty to create redirections in HTML, but as we can not save URL fragments in ZIM redirects, this is the only solution to make a redirect. This will have (almost) no impact neither on speed nor ZIM file size. This is easy to implement and will work everywhere and respect both ZIM / WebPlayers.js paradigms.

The fulltext search problem #19 is the last of my worries as there is an agreement that anyway the libzim will provide a solution which fix it, see https://github.com/openzim/libzim/issues/384.

> Actually, there is no reason why this has to be single page.. the service worker can also intercept any `/A/<...>` url and render the correct page.. That would not be hard to support, but you'd still need a separate endpoint from which to load raw content, eg. `/api/raw?article=...`

How do you want to secure that service-worker is loaded for a random URL like `https://example.com/zim_name/A/foo/bar.html` if this is just requested to the HTML rendere widget (or kiwix-serve)? AFAIK the service-worker just work withing the WebPlayer.js.

**Comment by ikreymer** [comment]
The linked PR switches to having the service worker keep the paths unchanged.. This allows for existing links to `/A/<...>` to be loaded by the service worker, and having search, suggestions and random all work.
Another option would be to redirect back to the single page view, which is also possible.
Basically the service worker can take over the rendering of these paths, transparent to the user.
This works because the service worker is registered in the entire `/A/` scope, not just for a single page.

**Comment by kelson42** [comment]
@ikreymer Thank you for giving a chance to experiment with that approach and hopefuly be able to evaluate properly is it brings more solutions than problems.
