### ISSUE TITLE
Zimit2: Add support for base href

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#238]
When a HTML page specifies a `<base href='xxx'>` in its `head` section, warc2zim does not take this into account for URL rewriting, causing mostly all links to be broken.

Sample page: https://www.radiozamaneh.com/section/culture

![image](https://github.com/openzim/warc2zim/assets/7102089/fc809f74-a7f3-4c3d-8621-03af4ecf4560)

The base href must be taken care of when rewriting URLs.

**Comment by kelson42** [comment]
Yes, had forgotten bout one... somehow surprised this was not already handled in version 1!

**Comment by Jaifroid** [comment]
I went through a lot of this pain when trying to emulate Replay Worker with regexes two or three years ago! I even have a note about problems with base href [here](https://github.com/kiwix/kiwix-js-pwa/blob/main/www/js/lib/transformZimit.js#L197):
```
// Remove any <base href...> statements
// DEV: You should probably deal with this more intelligently, changing absolute links rather than just removing,
// but so far, removing it seems to do the job
data = data.replace(/<base\b[^>]+href\b[^>]+>\s*/i, '');
```
Needless to say, don't follow that example!!

N.B. In version 1 with the Replay system, there should be no need to take care of this via URL transformations, because such relative base hrefs are read and interpreted by the browser, which modifies any URLs, SRCs, etc. that it fetches accordingly. The fetches are then caught by the Replay Service Worker and dealt with appropriately. Also, wombat.js takes care to transform any absolute base hrefs (https:...).

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/243
