### ISSUE TITLE
Zimit2: confirm last wombat setup arguments

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#239]
In Wombat setup code in warc2zim2, we have few arguments which are undocumented / weird.

```
    enable_auto_fetch: true,
    convert_post_to_get: true,
    target_frame: '___wb_replay_top_frame',
    isSW: true,
```

We need to confirm whether they are correct and why

**Comment by Jaifroid** [comment]
I can't help with the other values, but `target_frame: '___wb_replay_top_frame'` seems like a hangover from classic Zimit, where there is an actual iframe with that identifier that contains the rendered document, and which Wombat has to be injected into (I know because I set that up more or less "manually" in the classic Zimit support in KJS). That *should* no longer be relevant (but I've no idea if warc2zim2 works without it...).
