### ISSUE TITLE
LookupError: unknown encoding: unicode

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#331]
Not sure if still valid (we merged related stuff last week I think) but [this zimit.kiwix.org run](https://farm.zimit.kiwix.org/pipeline/2ce87ddd-2047-4b57-b181-0329fcdeb7c6/debug) failed in rewrite

```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 585, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 507, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/main.py", line 146, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 330, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 748, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/items.py", line 56, in __init__
    ).rewrite(pre_head_template, post_head_template)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 108, in rewrite
    return self.rewrite_html(pre_head_template, post_head_template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 247, in rewrite_html
    ).rewrite(self.content_str)
              ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 93, in content_str
    return to_string(
           ^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/utils.py", line 175, in to_string
    return input_.decode(head_encoding, errors="replace")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: unicode

```

**Comment by rgaudin** [comment]
And https://farm.zimit.kiwix.org/pipeline/2c1770f9-1281-48f0-ab8a-4bb2a727552b/debug

**Comment by benoit74** [comment]
Thank you!

**Comment by benoit74** [comment]
Same problem with `iso-utf-8` on https://farm.openzim.org/pipeline/d1fa0c7a-29c2-4229-80cf-686aba6ac0f5/debug

Note that on https://farm.zimit.kiwix.org/pipeline/2c1770f9-1281-48f0-ab8a-4bb2a727552b/debug the problem was with `iso-8559-1` (this is a typo, encoding is most probably `iso-8859-1`)

**Comment by benoit74** [comment]
Same kind of problem on page http://api.map.baidu.com/mapCard/js/finish/scriptURL.js where the charset is badly found with regex in JS code.

**Comment by benoit74** [comment]
Again with https://educacionenquimica.com.ar/index.php/edenlaq/article/download/76/135?inline=1 (`unicode`)

**Comment by benoit74** [comment]
Again with https://cdn.cookielaw.org/consent/796524c5-24c2-4cdf-907c-573192ba6a9d/otSDKStub.js (`this`), bad regex in JS code

**Comment by benoit74** [comment]
And
- https://mi_shell.gitlab.io/models_online/ose_webgl/js/three.min.js (JS problem also)
- https://wiki.opensourceecology.org/wiki/Main_Page (JS problem also)
- https://vercel.com/_next/static/chunks/83266-67bf9ae568a2b318.js?dpl=dpl_2hmfJkPd9Zdg3JRu5ruKqVazZ59j (JS problem also)
- https://tertullian.org/french/adversus_omnes_haereses.htm (`windows-utf-8` in HTML document)
- hhttps://www.answering-islam.org/Thai/index.html (`windows-874` in HTML document)

**Comment by benoit74** [comment]
It looks like there is two problems in one error log:
- the code trying to guess the charset in too permissive and grab a significant number of false positives in JS documents ; is there really a reason to run this regex on non-HTML documents? AFAIK, only HTML has a spec to declare charset in its header ; I suggest to detect charset in document header with regex only on HTML documents
- there is a variety of websites which provide wrong encodings, or at least encodings unknown in Python (`unicode`, `windows-utf-8`, `windows-874`, `iso-8559-1`, `iso-utf-8`) ; add automated support for these encodings is going to be cumbersome, because we never really know what is correct to use. I suggest that we simply add yet another parameter to configure additional (Python already has many) encoding aliases (`unicode=utf-8,iso-8559-1=iso-8859-1,windows-874=cp874`)

**Comment by pankajshakya627** [comment]
Similar kind of error I'm also getting while using AutoAWQ with LLAMA3-8B

```
model_path = "meta-llama/Meta-Llama-3-8B"
quant_path = "Meta-Llama-3-8B-AWQ-4bit"
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
model = AutoAWQForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True, trust_remote_code=True)
model.quantize(quant_path, quant_config=quant_config)

```




LookupError: unknown encoding: Estrogens interact in a variety of ways with the liver. Not only is the liver an estrogen-responsive tissue, but it is also responsible for the interconversion, metabolism and excretion of the estrogens. The effect of liver disease on these processes has not been studied well, except in the specific case of alcohol-induced liver disease. Therefore, using five well-characterized animal models of liver diseases, we will assess the effect of a variety of liver diseases on several aspects of estrogen metabolism in the male rat. First, the potential responsiveness of the liver to estrogens will be evaluated by quantitation of cytosolic receptors in both the diseased and normal livers as well as by determination of the affinity of the receptors for estrogen. Second, we will assess changes in the levels and/or affinity of male-specific estrogen binding protein whose proposed role is that of an estrogen scavenger. Third, the synthesis and tissue levels of the catechol estrogens (2-hydroxy estrogens) will be examined in rats with diseased and normal livers. These compounds are of interest because they are major metabolites of the estrogens in the liver, and, additionally, because they have been shown to interfere with P-450-related drug metabolism in the liver. Therefore, since alterations in any one of these various aspects of hepatic estrogen metabolism could adversely effect individuals with liver disease, an evaluation of various types ...


Any solution for the Lookup Error
