### ISSUE TITLE
ValueError: Incorrect HttpUrl scheme in value

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#332]
[This zimit run](https://farm.zimit.kiwix.org/pipeline/fb6ad63d-68f8-4315-80da-9c7878107e69/debug) failed rewriting an URL with an exotic scheme (`intent`).

```
ValueError: Incorrect HttpUrl scheme in value: intent://show/0vT7LJMeVDxyQ2ZamHKu08?si=_uDRD6bRR_6M5YZyISG
```

Non-`http`/`https` schemes are valid and should be ignored instead of being rewritten. Not sure if this statement is not in line with current implementation or if it's just a bug…

**Comment by benoit74** [comment]
If I'm not mistaken, non-http(s) schemes are ignored only when rewriting URLs. 

Here the error happens during the initial `gather_information_from_warc` where we loop over all entries, so I strongly suspect we have a WARC record associated with this URL. Didn't knew browsertrix crawler was capable of retrieving non-http(s) resources. Glad I implemented this check to avoid pushing stupid things to the ZIM. However such entries should probably just be ignored instead of raising an error and stopping the process.

**Comment by benoit74** [comment]
Previous assumption is wrong, problem lies in a redirect which is targeting these URLs with weird schemes, mostly same bug as #356 (just the error message differ)
