### ISSUE TITLE
HTML documents can also have `resourcetype` as `fetch`

### ISSUE THREAD

**Issue by adrian52999** [openzim/warc2zim#405]
Hello, I'm running into this weird issue:
I've archived a website but most of the links in it are not being opened in the built in browser, but externally in Firefox, requiring internet to load and thus eliminating the point in archiving them. I'm going to be specific:

I ran this command in docker:
docker run  -v [mydir]:/output ghcr.io/openzim/zimit zimit --url https://www.allaboutcircuits.com/ --name nameofthezim

Now this ran for a whopping 14 hours, resulting in a nearly 70GB zim file, and I thought nice, great, amazing. However, upon opening it I saw that not only most images have not been downloaded (which is likely due to me not using autoscroll in all honesty), but most links I click lead me to an external tab in my browser, which is Firefox. Upon right clicking on the both types of links (the ones that open in the built in browser, and the ones that open in FF) I've discovered that:

The ones that open in the built in browser have the option to Open Link In New Tab, while the the ones that open in FF have the option to Open Link In Web Browser.

Needless to say, this is a very severe issue, one could say a fatal one. I don't know what these 70GB consist of, because I run into external links in just a few clicks.

Any help would be greatly appreciated.

**Comment by adrian52999** [comment]
Thank you for the quick response, that sounds great! Sorry for the question but when you do release it do I have to update or change the way I type in the command?

I'd love to test it with depth 1 but the problem is that the links start getting wacky after around 2-3 clicks, which will take quite a bit more time to download and I'm out of time for today. I will test it later tonight and will let you know how it turns out.

Thank you again!

**Comment by benoit74** [comment]
> Sorry for the question but when you do release it do I have to update or change the way I type in the command?

You're welcome! Once release is done, you will have to refresh your Docker image with `docker pull ghcr.io/openzim/zimit`.

Or specify exactly which version you wanna use with `docker run -v [mydir]:/output ghcr.io/openzim/zimit:2.1.3 zimit --url https://www.allaboutcircuits.com/ --name nameofthezim`,  see the `2.1.3` I've added, because I know version I'm gonna release will be 2.1.3. You can watch releases at https://github.com/openzim/zimit/releases and updates of Docker which normally follow few minutes later at https://github.com/openzim/zimit/pkgs/container/zimit

> I'd love to test it with depth 1 but the problem is that the links start getting wacky after around 2-3 clicks, which will take quite a bit more time to download and I'm out of time for today. I will test it later tonight and will let you know how it turns out.

This was more a general remark than something to do right now, I have what I need to fix this bug. And if links gets wacky only after 2-3 clicks, then of course this trick is not going to work, sorry.

**Comment by benoit74** [comment]
FYI, new Docker image with the fix is ready to use.
