### ISSUE TITLE
Handle missing Service Worker scenarios

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#43]
With issues #10, #41 and in a way #24, we have important use cases broken because of the unavailability of the SW.

It seems logical a global approach would be used to solve them so here's the place to discuss what it could look like at both short and medium term.

A lot of discussion is happening on kiwixlib regarding the taskbar, raw content and APIs. It's important we track our options here with and without those features so we can participate in those discussions as well.

**Comment by rgaudin** [comment]
## Contribution: inserted payload

That's the inelegant solution that first comes to mind.
The idea is to inject a `<script />` into every HTML article that will be executed on load.

This script would have to figure out whether it is being invoked from a SW-enabled environment or not.
If it is not, then it would redirect to a special *redirect page* that would register the SW and then display
the appropriate article with it.

I've been able to get a POC working so there should not be much trouble with that solution.

```javascript
async function main() {
    if (window.frameElement) {
        // we're in an iframe
        console.log("zim:: in iframe, doing nothing.")
        return;
    }

    // we're not, probably not registered
    console.log("zim:: not in iframe, redirecting...");
    window.location.href = "/redirect?" + window.location.href;
}();
```

**Pros**:
- Easy to implement

**Cons**:
- not elegant (editing each HTML article to add a script tag)
- requires `text/html` MIME on articles, so a libkiwix fix for the taskbar. kiwix/kiwix-lib#391 kiwix/kiwix-lib#394

**Comment by rgaudin** [comment]
## Contribution: inserted payload via JS API

The (to-be-built) [JS API](https://wiki.openzim.org/wiki/Javascript_API) wants ZIM creators to be able to add a javascript file at a known location that would provide content-aware features to readers.
Those are not yet fully defined but we can imagine an *onload* endoint that would be executed each time an HTML article is loaded.

We could have the JS payload mentioned in the previous comment executed at this time.

_Note_: In the kiwix-serve context, the reader is kiwix-serve and would inject the JS API.

**Pros**:
- doesn't require us to edit content (readers will do that for us)

**Cons**:
- require JS API which is not defined and thus not implemented
- requires the `text/html` tweak also

**Comment by ikreymer** [comment]
Since libkiwix already does injection into HTML, and since this needs to be changed to support raw output, I think best option would be to support this at the libkiwix level simply by supporting a different insert than the taskbar or no insert at all.

Here's one way that this could be done, without requiring a specific service worker implementation or iframes in libkiwix

- Add a `M/ServiceWorkerEntry` metadata. If not set, keep current behavior, no changes.

- If `M/ServiceWorkerEntry` is set to the main service worker entry point url (maybe A/register.html)
    - If a request to libkiwix, check is a special header is set, like `Prefer: raw` (one header that has been used before) that can be set only by the service worker. If it is set, serve raw content with no rewriting.
    - If special header is not set, then rewrite, but with a different insert, something like the example above, instead of the taskbar header.

This will allow for modifying the header at the libkiwix level, rather than inserting into every ZIM article, and also solves the raw `text/html` issue.

The inserted header can check several things:
 - If `navigator.serviceWorker` is null, service workers are not available and an error should be displayed.
 - if `navigator.serviceWorker` is not null, but `navigator.serviceWorker.controller` is null, then service workers are available, but not registered, so redirect to 'entry point page' (from `M/ServiceWorkerEntry`), maybe with a redirect back, so `/register.html?#redirect=/A/example.com/somearticle.html`. This will go to register.html to register the service worker, then redirect back to the article with service worker enabled.
 - if `navigator.serviceWorker.controller` is not null, then service worker is already registered, but this was most likely a hard refresh. Just do a regular `window.reload()`

**Comment by kelson42** [comment]
> Since libkiwix already does injection into HTML, and since this needs to be changed to support raw output, I think best option would be to support this at the libkiwix level simply by supporting a different insert than the taskbar or no insert at all.

Just a few remarks:
* This DOM modification is not something we are actually really proud of and we would better avoid
* We do that only for kiwix-serve, here this would be needed everywhere

**Comment by ikreymer** [comment]
> > Since libkiwix already does injection into HTML, and since this needs to be changed to support raw output, I think best option would be to support this at the libkiwix level simply by supporting a different insert than the taskbar or no insert at all.
> 
> Just a few remarks:
> 
> * This DOM modification is not something we are actually really proud of and we would better avoid
> * We do that only for kiwix-serve, here this would be needed everywhere

Yes, but if alternative is to do DOM modification on every article in ZIM, I think it is still much better to do this at replay time. Otherwise, entire ZIMs would need to be redone if any change at all is needed, rather than releasing a new version.

It looks like the existing insertion functionality is entirely in libkiwix (https://github.com/kiwix/kiwix-lib/blob/master/src/server/response.cpp#L189), so the above behavior could be made available on all platforms.

The default (no M/ServiceWorkerEntry) would of course keep current behavior - no changes except in kiwix-serve.

**Comment by ikreymer** [comment]
I think the replay system will always need to modify the raw data in some way to encapsulate it, whether on the server on at the service worker level, usually as late as possible, but this is to be expected. If we know there's no service worker, then it must be done on the server.
Modifying the raw data with parts of replay system (javascript to check for sw, etc...) is a worse solution since it will make maintenance that much harder. If some different solution will be needed because something about SW changes, or a better replay option comes along, old ZIMs may break, so I really think injecting this into ZIM should be avoided if at all possible..

**Comment by rgaudin** [comment]
@ikreymer I hope the title wasn't misleading. The goal is not to evaluate getting rid of the SW completely but to mitigate the issues users face when SW is not working as expected (#10 #24 #41)

We've discussed this with @kelson42 and decided the following next steps:

* kiwix-lib is about to allow raw retrieval of article content (https://github.com/kiwix/kiwix-lib/pull/403)
* We switch MIME to `text/html;raw=true`
* We implement the *inserted payload* option (first comment), making sure we have the 3 failing cases supported.

The reasonning is that this is quite easy to implement and doesn't require much architecture change. With this implemented, we'll have a first working version and we can think about the better way to handle this without being in a rush. There are many open questions and we can't both make informed one and be ready tomorrow.
