### ISSUE TITLE
Videos not working on android

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#55]
Using latest fondamentaux zim, videos all fail to load.

Console shows `NET_ERR` attempting to fetch `https://kiwix.app/A/oe_///cdn.reseau-canope.fr/medias/lesfondamentaux/0204_hd.mp4`

Pointing the browser at that exact location triggers the video UI of the browser but it spins forever and the console prints the same message.

<img width="950" alt="Screenshot 2020-08-20 at 11 50 22" src="https://user-images.githubusercontent.com/57929/90755355-57625a00-e2db-11ea-9b22-116fb73a4c15.png">

**Comment by ikreymer** [comment]
Hm, I'll try to set up an emulator to take a look. Hopefully something simple, but want to understand the issue.

**Comment by kelson42** [comment]
@rgaudin @ikreymer What is the status here, quite a serious problem?

**Comment by ikreymer** [comment]
It appears the android client is not handling range requests correctly.

Given a range request, it looks like it does return the range and sets the content-length, but it also needs to:
- Set status code to 206
- Set `Content-Range` header (eg something like: `Content-Range: bytes 20381696-20532194/20532195` in this example)

The wabac.js is checking for the 206 status code in particular to ensure that it has actually gotten arrange.
Otherwise, it assumes that it did not get a range, and will try to skip and seek on its own (which is not fully supported yet)
Probably needs a better error message on my end as well.

But return a 206 in android client should fix the issue.

<img width="834" alt="Screen Shot 2020-08-29 at 8 25 31 PM" src="https://user-images.githubusercontent.com/1015759/91650630-c73cb700-ea36-11ea-897b-be1d36284a07.png">

I'll open an issue in kiwix-android and link to this example.

**Comment by kelson42** [comment]
This has been fixed. Closing.
