### ISSUE TITLE
Caching/Refreshing does not always work fine

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#66]
Here is how the button looks like:
![image](https://user-images.githubusercontent.com/1029718/97289236-36703500-1847-11eb-94ca-99df68541856.png)

We can see the button text is "Accueil - les anim..." but it should be "Les Fondamentaux" like specified at https://tukasu.ml/les-fondamentaux_fr_all/M/Title.

As this problem seems to occurs only with Zimit ZIM files (not all of them) and as well because we tend to see that the label of the button changes quickly at page loading, I believe we have a piece of javascript somewhere in the ZIM at the source of that bug.

**Comment by kelson42** [comment]
I have transfered the issue to `openzim/warc2zim` and want to add a few new information:
* The original problem impact FF as well. There might be a Chrome specific problem, but FF users are impacted as well.
* The impacts goes bayond this problem with the button. For example, if I restart the kiwix-serve with `--blockexternal` which is an important use case in PROD, then this feature does not apply on already cached resources.

**Comment by kelson42** [comment]
@ikreymer Thank you for your investigation and interesting last comment. I believe you nailed it, `etag` will be checked with an additional upstream HTTP request ONLY if the cache has expired. As a consequence, the problem is not ETAG at all, the problem is that we have the resources cached and that it is legitimately used.

We should now have a strategy to solve the problem. You propose a `--nocache` but this is "too brutal" to me. What I would like to know is which content delivered by the kiwix-serve is concerned by behaviour? Obviously images are not, but does that concern all the rest?

**Comment by ikreymer** [comment]
If we are talking about loading a new ZIM in place of an older one with the same name as a previous ZIM, then it could be any resource. Since the previous ZIM might have been incorrect, we always want to test the new version without anything from the older file interfering. Maybe images too if something was wrong with the previous crawl. Thats why I suggested disabling the cache for everything, since we want to test a new file cleanly. The other option is of course to open an incognito window in Chrome.

**Comment by kelson42** [comment]
@ikreymer I think the only thing we can for the moment clearly say to be buggy is that the CTRL+SHIPT+R does not achieve to refresh the page. Do you agree on that? Should I open a new ticket for it?

**Comment by ikreymer** [comment]
No, there's not much we can do about that behavior. The reason is that everything is loaded dynamically via `fetch()` and not directly by the browser, and fetch() follows the default headers unless it is explicitly disabled. And it is not possible to detect if a page was loaded with Ctrl+Shirt+R or normally in JS: https://stackoverflow.com/questions/54040182/detect-a-hard-reload-with-javascript

**Comment by rgaudin** [comment]
> The other option is of course to open an incognito window in Chrome.

Ans this is because Chrome allows Service Worker in incognito mode while Firefox doesn't…

**Comment by kelson42** [comment]
Even if this is not a blocker, I’m worried about that ticket... but would this does not seem critical. Would like to postpone the discussion.

**Comment by kelson42** [comment]
We should recheck this after https://github.com/kiwix/libkiwix/issues/650 is fixed.

**Comment by kelson42** [comment]
@rgaudin What do you think about closing this ticket? Same as https://github.com/openzim/zimit/issues/154 IMO.

**Comment by rgaudin** [comment]
Closing as too old
