### ISSUE TITLE
Improper home as redirect handling

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#67]
When the main_page doesn't respond with HTML content a couple of things are not done properly:

- the following condition leads only to a warning without other action. Shouldn't the content-reading part be on an else clause? Those reads will lead to nothing in best case (no content) or might crash (if trying to soup a binary file)

https://github.com/openzim/warc2zim/blob/45cfbe2d3cabbea20eab1ee194c736ca1515cfd9/src/warc2zim/main.py#L439-L444

- the actual main page (target of the main_page's redirect) is not looked for so the title and favicon are not extracted properly.

We could follow the redirection (maybe watching for a circular loop there) and act upon the actual main_page

**Comment by ikreymer** [comment]
Ah nice, catch, yes it should probably return there.

For the redirect, there could be a number of complications, one is self-redirect, another is there could be multiple redirects, not just one, and even a redirect to a different domain. Since the content is processed in a stream, the redirected to records could be ahead, or could already have been processed.
I think this adds a lot of complications.
Instead, perhaps zimit should just check if the `--url` parameter is a valid response returning a 200, and maybe even require that it be HTML?
That will make it easier to detect errors as the recipe will fail quickly if there is a typo.
I think that may be the best solution, since its very easy to just adjust the URL to `https://lesfondamentaux.reseau-canope.fr/accueil.html` instead of `https://lesfondamentaux.reseau-canope.fr/` if there is a clear error message.

**Comment by rgaudin** [comment]
Following up on https://github.com/openzim/zimit/issues/42 I think we can indeed fail early with non-200 main page. As for failing non-html 200 main pages, I'd say no for now.
