### ISSUE TITLE
Direct linking to page with query string when service worker is not installed will not work.

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#70]
This is a special case of the issue fixed in #47.

When visiting a direct link with no service worker installed, the system will redirect to the index page and install the service worker.

However, if the page is not found, then it will just show the default kiwix-serve page. This can occur if there is a query string, since kiwix-serve does not handle that correctly, but the service worker does.

For example, loading: `https://kiwix-dev.webrecorder.net/zim/A/www.example.com/` will install the service worker correctly, but loading `https://kiwix-dev.webrecorder.net/asb_2020-11/A/www.example.com/?query=string` will not, because kiwix-serve will not find the page `A/www.example.com/?query=string` and serve the standard 404 page.

Once the service worker is installed, `https://kiwix-dev.webrecorder.net/asb_2020-11/A/www.example.com/?query=string` will be handled correctly.

Just wanted to flag this -- I think the only solution is to be able to customize the 404 page that is served when there is no service worker yet. This would part of making the system service-worker aware.

**Comment by kelson42** [comment]
@ikreymer @rgaudin Do we know if we still suffer of this bug?

**Comment by rgaudin** [comment]
Of course, it's a limitation of kiwix-serve.

Keep in mind that it concerns:
- direct links which includes a query string
- in the situation the SW is not (yet) installed

Example (with the SW installed):
- Go to https://dev.library.kiwix.org/viewer#ki4u_2023-03/A/kiwix.com/AAA?attr1=value1&attr2=value2
- Arrive at https://dev.library.kiwix.org/viewer#ki4u_2023-03/A/kiwix.com/AAA with content: Sorry, the url https://kiwix.com/AAA?attr1=value1&attr2=value2 is not found on this server.
 
That's because the frame URL is https://dev.library.kiwix.org/content/ki4u_2023-03/A/mp_/https://kiwix.com/AAA?attr1=value1&attr2=value2

Example (without SW installed):
- Go to https://dev.library.kiwix.org/viewer#ki4u_2023-03/A/kiwix.com/AAA?attr1=value1&attr2=value2
- Arrive at https://dev.library.kiwix.org/viewer#ki4u_2023-03/A/kiwix.com/AAA with content Not Found / The requested URL "/content/ki4u_2023-03/A/kiwix.com/[AAA](https://dev.library.kiwix.org/search?content=ki4u_2023-03&pattern=AAA)" was not found on this server. / Make a full text search for AAA

That's because only kiwix-serve was involved and it doesn't account for query strings.

**Comment by kelson42** [comment]
@benoit74 This ticket deserves a "zimit2" update IMHO.

**Comment by benoit74** [comment]
Indeed, this will "automatically" be solved by zimit2. Closing since "no (more) work needed", the move to zimit2 will induce getting rid of SW, so we won't have anymore problem of SW installed or not.
