### ISSUE TITLE
Optimize multimedia content and cache it

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#72]
To reduce the size of images and ultimatively the ZIM file.

**Comment by rgaudin** [comment]
@kelson42 have your opinion evolved regarding this?

- most size consuming resources are likely videos
- we can't reasonably change format so the most we could do is apply more aggressive compression.
- we wont be able to assess quality and given we don't even test ZIMs properly, I doubt we'd do it anyway
- we'd have to mangle with the warc headers as well (because Content-Length would change)
- video is already fragile and we don't know about side effects
- streaming platforms may have resources in unexpected locations and mimetype. that another thing to maintain

So I'm not in favor of pursuing this at the moment. Do we have a ZIM in our catalog for which the videos are unreasonably large?

One easier alternative would be to introduce a crawling feature to fake a slower connection (ideally only on platforms that auto-detect and adjust resolution to bandwidth) so we crawl lower resolutions. That would be at the expense of crawling speed of course but that seems preferable to me.

**Comment by kelson42** [comment]
@rgaudin This is necessary to do it - for exactly the same reasons as for other scrapers -  IMO. It mostly concerns pictures, not videos. That said, clearly not the prio of the moment.

**Comment by kelson42** [comment]
For the moment, probably not worth the effort. Closing and I will reopen if someone else request it.
