### ISSUE TITLE
Incorrect charset encoding indicated in meta tag of some warc2zim archives

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#88]
OpenZIM spec says that all text files (html, css, js) stored in a ZIM must be UTF8-encoded. Warc2zim does not seem to implement this. For example, in `bouquineux.com_fr_all_2022-02.zim` the main HTML files are iso-8859-1, leading to the kind of failure seen in screenshot below. This is obviously a tricky issue, because decoding UTF8 data is pretty much hard-baked into Kiwix readers (I believe) given that there is no character-encoding field in a dirEntry.

Any thoughts on how clients can deal with this? Maybe the response header will give us the encoding before we decode any data? On the other hand, it would be much better if warc2zim handled this and translated non-UTF8 data into UTF8 before storing in the ZIM (it would then conform to spec).

![image](https://user-images.githubusercontent.com/4304337/170817541-93160e4d-80aa-435a-8bba-e4617ce437d5.png)

Tagging @mossroy as this kind of issue is relevant for upcoming discussion.

**Comment by rgaudin** [comment]
Indeed [the spec](https://wiki.openzim.org/wiki/Article_Format) requests *Article Entries* to be UTF-8 encoded.
Given warc2zim stores WARC payload that requires loading WARC headers (which contains the Content-Type) to be accessed, I suppose those might be considered resources… especially now that there is no namespace segregation anymore.
We have an HTML shim for each Article I believe that is used for direct links (should the SW not be installed yet).

I suggest we add two topics to the discussion:
- Add this to the list of warc2zim specificities, obviously
- Discuss whether this requirement is still valid (*articles* required to be UTF-8).

**Comment by kelson42** [comment]
@Jaifroid We have a serious problem indeed here because (1) We can hardly change the charset of the document (2) Do we really want to change the spec on this?!?

AFAIK, the HTML DOM node header should be enough to display properly the content. But we could consider to have a ZIM article with the charset specfied:`text/html; charset=ISO-8859-1`. What would be necessary on your end to get this working properly?

In any case, I suspect that we will have to change the spec if we really want to be coherent here.

**Comment by Jaifroid** [comment]
> Given warc2zim stores WARC payload that requires loading WARC headers (which contains the Content-Type) to be accessed, I suppose those might be considered resources… especially now that there is no namespace segregation anymore.

Yes the ZIM stores WARC response headers, and I suppose the way for a reader to deal with this is to inspect the header for the content type and then decode accordingly. However, articles, css, js, etc. are **all** still stored under the `A/` namespace (future `C/` namespace) as Uint8Arrays, and at a low level, to convert this to a text string (when needed), we do decode the array as UTF8, because that's what the spec says we can assume.

The issue can be dealt with by adding more logic in the reader. Libzim might not be impacted if it never decodes the Uint8Arrays to UTF-8.

This issue might also be a legacy issue, as most modern websites use UTF-8 as standard.

**Comment by Jaifroid** [comment]
Strangely, to read at least `bouquineux.com_fr_all_2022-02.zim` all that is needed is to delete the character set assignment in the HTML meta tag. This means that articles in this ZIM are in fact encoded as UTF-8, but the meta tag is incorrect. Could it be that warc2zim in fact converts and stores textual data as UTF-8, but that it doesn't then handle changing the meta tag in HTML? 

See the corrected display of the same article above below, simply removing the meta tag.

So I guess this is still a bug, but a different one from what I thought. (Also an easier one to deal with in warc2zim.)

![image](https://user-images.githubusercontent.com/4304337/170824932-ddca90c5-b098-4cd7-8a63-0a8feea45ffe.png)

**Comment by kelson42** [comment]
> This means that articles in this ZIM are in fact encoded as UTF-8, but the meta tag is incorrect.

Yes, see also https://validator.w3.org/check?uri=http%3A%2F%2Fbouquineux.com%2F%3Febooks%3D403%26Scud%25C3%25A9ry&charset=%28detect+automatically%29&doctype=Inline&group=0

The HTML DOM nodes are not edited at all during the scraping. That is true.

Actually, here the bug is that the source HTML is wrong. But if it would be real `iso-latin-1`, then we would have a real problem. Thereforre, even if the example is bad, the ticket is still valid IMO.

**Comment by mgautierfr** [comment]
> Indeed [the spec](https://wiki.openzim.org/wiki/Article_Format) requests Article Entries to be UTF-8 encoded.
> Discuss whether this requirement is still valid (articles required to be UTF-8).

I have always found a bit odd that a archive format enforce an encoded of the content. It would be the same kind of restriction telling that images must be png. 
It is ok for me that a encoding is force for the path of the entries (as libzim will manipulate them) or force the format of some specific entries (utf8 encoding for metadata, png for favicon). But if we are scrapping a website, we probably want to store the content in the encoding of the website, not some mandatory encoding (regardless of the quality of this encoding)

But in the same time I understand the requirement as it add a constraint on the creator and allow the reader to assume utf8 everywhere (until it is not the case, or something is lying about the encoding)

---

And the bug is probably that the scrapper encode the content to utf8 for this part of the spec and forget about changing the header telling the encoding. (And this is somehow a complex thing to do correctly)

---

W3C https://www.w3.org/International/questions/qa-html-encoding-declarations.en tell us about character encoding and declaration of it.

Among other things, it is told:

> Using UTF-8 not only simplifies authoring of pages, it avoids unexpected results on form submission and URL encodings, which use the document's character encoding by default.

Which is an argument to enforce utf8 encoding of the content as it will be the encoding of the url (and we need utf8 here)

**Comment by kelson42** [comment]
I have reported the error with bouquineux.com upstream here https://twitter.com/KiwixOffline/status/1531537803946905600

**Comment by rgaudin** [comment]
Have re-read the ticket and am not sure about what to do next. I want to stay we hold this until we have a problematic real-world example.

**Comment by Jaifroid** [comment]
I worked around the problems in my implementation some time ago -- at least I haven't encountered odd character encodings in the rendered HTML, though it's fair to say that almost all modern sites have switched to UTF8 universally. Therefore this is probably a legacy issue that would be nice to have a solution for, but in the real world probably not necessary to fix. The issue could be closed as it's referenced in #86 and can be followed up by anyone encountering it in the future. So, since I opened it, I'm closing it, but feel free to re-open any time of course.
